### ISSUE TITLE
Errors with additional_files.

### ISSUE THREAD

**Issue by vanillahsu** [18Months/distillery_packager#1]
I always got error when I add additional_files on deb_package(),
and it seems the wrong usage of File:cp_r/2

please help to check, thanks.

--------------------------------------------------------------------
==> Assembling release..
==> Building release xxx:0.0.1 using environment prod
==> Including ERTS 8.3 from /usr/lib/erlang/erts-8.3
==> Building Deb Package
==> Created /home/vanilla/xxx/_build/prod/deb/data/etc/xxx directory for additional files
==> Copy /home/vanilla/xxx/rel/distillery_packager/debian/additional_files/configs into /home/vanilla/xxx/_build/prod/deb/data/etc/xxx directory failed eisdir /home/vanilla/xxx/rel/distillery_packager/debian/additional_files/configs
==> Using user-provided file: upstart.conf.eex
--------------------------------------------------------------------

**Comment by samuelebistoletti** [comment]
Hi, I think you have to set the configuration in mix.exs in the right way. As you can see from the README source and target must be folders, not single files.
If you're not sure about that, can you please paste additional_files row in mix file here? And a screen of your directory tree under rel/distillery_packager/debian/additional_files?

**Comment by vanillahsu** [comment]
Thanks for your quick reply,

I change source as directory, and it works, (my fault, sorry)
