### ISSUE TITLE
Needs updates for distillery v 2.1.1 

### ISSUE THREAD

**Issue by carthik** [18Months/distillery_packager#11]
Currently, I get the following error:
```
==> distillery_packager

Compiling 16 files (.ex)


== Compilation error in file lib/plugin.ex ==

** (CompileError) lib/plugin.ex:6: module Mix.Releases.Plugin is not loaded and could not be found

    (elixir) expanding macro: Kernel.use/1

    lib/plugin.ex:6: DistilleryPackager.Plugin (module)

could not compile dependency :distillery_packager, "mix compile" failed. You can recompile this dependency with "mix deps.compile distillery_packager", update it with "mix deps.update distillery_packager" or clean it with "mix deps.clean distillery_packager"

script returned exit code 1
```

as I understand it, this change in distillery would affect distillery_packager:
https://github.com/bitwalker/distillery/commit/48b8aa0b875dd5eda0b1d21186046612aeb9323e#diff-343723a0cb380f664aedf0dfed5c1c2fR17

**Comment by samuelebistoletti** [comment]
This would need more testing. Also the last version of Elixir (1.9) includes releases, so this library would need some refactory. A PR is always welcome, but at the moment I have no time to fix this.

**Comment by samuelebistoletti** [comment]
I tried an update on the fly, mix test is ok, but it would be useful some more testing on real case. If someone could try that and it's ok I will merge the development branch to master, and release a new version.

thanks

**Comment by carthik** [comment]
@samuelebistoletti  - Thank you! I have been using the `development` version without issues for a couple of days since you made the changes. No errors with the packaging.

**Comment by monkeygroover** [comment]
@samuelebistoletti Thanks! this works fine for me too.

**Comment by carthik** [comment]
Can you please release a new version with the fix? Thanks for your help with this!

**Comment by samuelebistoletti** [comment]
New version released!
