### ISSUE TITLE
Elixir 1.11 EEx newline behavior change

### ISSUE THREAD

**Issue by k-cross** [18Months/distillery_packager#15]
I created a ticket in the elixir language documented here:
https://github.com/elixir-lang/elixir/issues/10651

It will not be fixed but I have a PR open to address the issue. In case that PR isn't desirable, I'll leave the issue open for tracking.

**Comment by samuelebistoletti** [comment]
Hi, merged now, sorry for the very big delay. I will release the new version as soon as possible
