### ISSUE TITLE
Provide option to *not* build init scripts

### ISSUE THREAD

**Issue by rlipscombe** [18Months/distillery_packager#9]
It appears that the upstart/systemd/SysV init scripts are always generated. Is there any way to disable this? If not, could one be added?

**Comment by samuelebistoletti** [comment]
No, there is not a way to disable it at the moment. It is not in plan such a development in short time, but any pull request is welcome.
Also consider that the OS will use only the right script, depending on which service management is running on your system. This was done to cover all the possibility in one shot.

**Comment by rlipscombe** [comment]
> Also consider that the OS will use only the right script, depending on which service management is running on your system.

The point is that I need to deploy a custom init script (to set some environment variables); having one already in the package requires some workarounds in our deploy process (i.e. chef).

**Comment by rlipscombe** [comment]
I know that I can extract (and customize) the templates used. That's pretty cool. My problem is that this needs to be done at deploy time, not at build time, so we'd prefer not to have the files at all.

**Comment by rlipscombe** [comment]
But it's your project, and your decision. We'll deal with it.

**Comment by samuelebistoletti** [comment]
Ok, I understand that, there is no way at the moment, but I agree with the need to have such an option. Unfortunately at the moment I have no time to develop it. Maybe in the next future. I will reopen the issue for now..
